atomAdminCommand.label = Folder Utility
atomAdminUtils.name = Folder Utility
atomAdminChangeItemAtribute.name = Change Items Attribute
atomAdminChangeItemID.name = Change Item ID
atomAdminLoadElements.name = Load Items
atomAdminCreateElements.name = Create Items