atomAdminCommand.label = Folder Utility
atomAdminUtils.name = Folder Utility
atomAdminChangeItemAtribute.name = Change Item Attribute
atomAdminChangeItemID.name = Change Item ID
atomAdminLoadElements.name = Load Elements